server:
  port: 12000
spring:  #连接远程Git仓库地址
  application:
    name: ts-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tangijia/ts-config.git
  #          username: 2656259928@qq.com
  #          password: 密码不告诉你
  rabbitmq:
    host: 192.168.195.135
management:  #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh

