server: 
  port: 9008
spring: 
  application:  
    name: ts-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.135:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.195.135
  redis:
    host: 192.168.195.135
    port: 6379
# JWT
jwt:
  config:
    key: rumoss
    ttl: 360000