# 配置tomcat端口号
server:
  port: 9004
# 配置注册中心中当前应用名称，名称不要有下划线_
spring:
  application:
    name: ts-article
  datasource:
    url: jdbc:mysql://192.168.195.135:3306/tensquare_article?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 192.168.195.135
    port: 6379
  data:
    mongodb:
      host: 192.168.195.136
      port: 27017
      database: articledb
