# 配置tomcat端口号
server:
  port: 9010
# 配置注册中心中当前应用名称，名称不要有下划线_
spring:
  application:
    name: ts-friend
  datasource:
    url: jdbc:mysql://192.168.195.135:3306/tensquare_qa?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
# JWT
jwt:
  config:
    key: rumoss
    ttl: 3600000
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka   #指定Eureka注册地址
